baseURL: http://sunnycloudyang.top/
languageCode: en
defaultContentLanguage: en
title: TradeMall
theme: hugo-universal-theme

googleAnalytics: ""
summaryLength: 20
paginate: 10
pluralizelisttitles: false
publishDir: docs

menu:
  main:
    - name: "Home"
      identifier: "menu.home"
      url: ""
      weight: 1

    - name: "Products"
      identifier: "menu.products"
      # url: "/products/"
      weight: 2
    - name: "By Category"
      post: 1
      url: "/products/"
      role: separator
      identifier: "section.by-category"
      weight: 100
      parent: "menu.products"
    - name: "Apparel"
      url: "/products/%40category%3Dapparel"
      weight: 200
      parent: "section.by-category"
    - name: "Bags & Totes"
      url: "/products/%40category%3Dbags-totes"
      weight: 300
      parent: "section.by-category"
    - name: "Clothes"
      url: "/products/%40category%3Dclothes"
      weight: 365
      parent: "section.by-category"
    - name: "Drinkware"
      url: "/products/%40category%3Ddrinkware"
      weight: 400
      parent: "section.by-category"
    - name: "Electronics"
      url: "/products/%40category%3Delectronics"
      weight: 500
      parent: "section.by-category"
    - name: "Office"
      url: "/products/%40category%3Doffice"
      weight: 600
      parent: "section.by-category"
    - name: "Writing"
      url: "/products/%40category%3Dwriting"
      weight: 700
      parent: "section.by-category"
    - name: "Wellness"
      url: "/products/%40category%3Dwellness"
      weight: 800
      parent: "section.by-category"

    - name: "By Theme"
      url: "/products/"
      post: 2
      role: separator
      identifier: "section.by-theme"
      weight: 1300
      parent: "menu.products"

    - name: "Holiday"
      url: "/products/%40theme%3Dholiday"
      weight: 1400
      parent: "section.by-theme"
    - name: "Spring"
      url: "/products/%40theme%3Dspring"
      weight: 1500
      parent: "section.by-theme"
    - name: "Summer"
      url: "/products/%40theme%3Dsummer"
      weight: 1600
      parent: "section.by-theme"
    - name: "Fall"
      url: "/products/%40theme%3Dfall"
      weight: 1700
      parent: "section.by-theme"
    - name: "Winter"
      url: "/products/%40theme%3Dwinter"
      weight: 1800
      parent: "section.by-theme"

    - name: "By Price"
      url: "/products/"
      post: 3
      role: separator
      identifier: "section.by-price"
      weight: 900
      parent: "menu.products"

    - name: "$1 or Less"
      url: "/products/%40price%3C1"
      weight: 1000
      parent: "section.by-price"
    - name: "$1 - $10"
      url: "/products/%40price%3E1%26price%3C10"
      weight: 1100
      parent: "section.by-price"
    - name: "$10 or More"
      url: "/products/%40price%3E10"
      weight: 1200
      parent: "section.by-price"


    - name: "services"
      identifier: "menu.services"
      url: "/services/"
      weight: 3
    # - name: "KITTING"
    #   url: "/services/kitting/"
    #   weight: 100
    #   parent: "menu.services"
    # - name: "idea to product"
    #   url: "/services/idea-to-product/"
    #   weight: 200
    #   parent: "menu.services"
    # - name: "package design"
    #   url: "/services/package-design/"
    #   weight: 300
    #   parent: "menu.services"
    # - name: "drop shipping"
    #   url: "/services/drop-shipping/"
    #   weight: 400
    #   parent: "menu.services"

    - name: "FAQ"
      identifier: "faq"
      url: "/faq/"
      weight: 4

    - name: "Contact"
      identifier: "contact"
      url: "/contact/"
      weight: 5

    - name: "Login"
      identifier: "login"
      url: "/login/"
      weight: 6

  topbar:
    - weight: 1
      name: Upload
      url: /products/upload/
      pre: <i class='fas fa-2x fa-upload'></i>
    - weight: 2
      name: Admin
      url: /admin/
      pre: <i class='fas fa-2x fa-user'></i>
    - weight: 3
      name: Phone
      url: tel:+12 34 567 89 01
      pre: <i class='fas fa-2x fa-phone'></i>
    # - weight: 4
    #   name: GitHub
    #   url: https://github.com/devcows/hugo-universal-theme
    #   pre: <i class='fab fa-2x fa-github'></i>
    # - weight: 5
    #   name: Facebook
    #   url: http://facebook.com
    #   pre: <i class='fab fa-2x fa-facebook'></i>
    # - weight: 6
    #   name: Twitter
    #   url: http://twitter.com
    #   pre: <i class='fab fa-2x fa-twitter'></i>
    - weight: 7
      name: Email
      url: mailto:hello@universal.com
      pre: <i class='fas fa-2x fa-envelope'></i>

params:
  viewMorePostLink: /services/
  author: DevCows
  defaultKeywords:
    - devcows
    - hugo
    - go
  mainSections:
    # - blog
    - services
  defaultDescription: Site template made by Devcows using Hugo
  facebook_site: ""
  twitter_site: GoHugoIO
  default_sharing_image: img/sharing-default.png

  enableGoogleMaps: false
  googleMapsApiKey: AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY
  latitude: "-12.043333"
  longitude: "-77.028333"

  style: default
  formspree_action: https://formspree.io/sample/of/endpoint
  contact_form_ajax: false

  enableRecaptchaInContactForm: false
  enableRecaptchaInLoginForm: false
  googleRecaptchaKey: site_key_for_google_recaptcha

  about_us: <p>Pellentesque habitant morbi tristique senectus et netus et
    malesuada fames ac turpis egestas.</p>
  copyright: Copyright (c) 2015 - 2016, YourCompany; all rights reserved.
  date_format: January 2, 2006

  dropdown_mouse_over: false
  enableDropdownFix: true

  disabled_logo: false
  logo_text: Universal
  logo: img/logo.png
  logo_small: img/logo-small.png
  bannerFullWidth: true

  preserveTaxonomyNames: true

  contact_url: /contact
  address: "<p class=\"text-uppercase\"><strong>Universal Ltd.</strong>
    \        <br>13/25 New Avenue
    \        <br>Newtown upon River
    \        <br>45Y 73J
    \        <br>England
    \        <br>
    \        <strong>Great Britain</strong>
    \      </p>
    \      "

  topbar:
    enable: true
    text: "<p class=\"hidden-sm hidden-xs\">Contact us on +420 777 555 333 or
      hello@universal.com.</p>
      \      <p class=\"hidden-md hidden-lg\"><a href=\"tel:+420 777 555
      333\" data-animate-hover=\"pulse\"><i class=\"fas fa-phone\"></i></a>
      \      <a href=\"mailto:hello@universal.com\"
      data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>
      \      </p>
      \      "

  disableSidebar: true
  widgets:
    categories: false
    tags: false
    search: false

  carouselCustomers:
    items: 6
    auto_play: false
    slide_speed: 2000
    pagination_speed: 1000

  carouselTestimonials:
    items: 4
    auto_play: false
    slide_speed: 2000
    pagination_speed: 1000

  carouselHomepage:
    enable: true
    auto_play: true
    slide_speed: 2000
    pagination_speed: 1000

  features:
    enable: true
    cols: 3

  testimonials:
    enable: true
    title: Testimonials
    subtitle:
      We have worked with many clients and we always like to hear they come
      out from the cooperation happy and satisfied. Have a look what our clients
      said about us.

  see_more:
    enable: true
    icon: far fa-file-alt
    title: Do you want to see more?
    subtitle:
      We have prepared for you more than 40 different HTML pages, including
      5 variations of homepage.
    link_url: "/products/"
    link_text: Go to our products

  clients:
    enable: true
    title: Our Clients
    subtitle: ""

  recent_posts:
    enable: true
    title: Our Services
    subtitle:
      Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
    hide_summary: false

  footer:
    recent_posts:
      enable: false

permalinks:
  # blog: /blog/:year/:month/:day/:filename/
  services: /services/:filename/
taxonomies:
  category: categories
  tag: tags
  author: authors
