# [build]
#   publish = "docs"
#   command = "hugo -F --cleanDestinationDir"
#   [build.environment]
#     HUGO_VERSION = "0.109.0"

# [context.production.environment]
#   HUGO_ENV           = "production"
#   HUGO_ENABLEGITINFO = "true"

# [context.split1]
#   command = "hugo -F --cleanDestinationDir --enableGitInfo"

#   [context.split1.environment]
#     HUGO_ENV = "production"

# [context.deploy-preview]
#   command = "hugo -F --cleanDestinationDir --buildFuture -b $DEPLOY_PRIME_URL"

# [context.branch-deploy]
#   command = "hugo -F --cleanDestinationDir -b $DEPLOY_PRIME_URL"

# [context.next.environment]
#   HUGO_ENABLEGITINFO = "true"

# [[redirects]]
#   from   = "/npmjs/*"
#   to     = "/npmjs/"
#   status = 200